name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

permissions:
  contents: read
  packages: write

env:
  BASE_IMAGE: mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-aot
  BASE_IMAGE_SINGLE: mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled
  DOCKER_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && 'latest;edge' || 'edge' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    outputs:
      full-version: ${{ steps.bootstrap.outputs.full-version }}
      major-version: ${{ steps.bootstrap.outputs.major-version }}
    needs: [build]

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - id: repo-basename
        run: 'echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT'
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5.0.0
      - name: Build documentation
        uses: elastic/docs-builder@main
        with:
          prefix: '${{ steps.repo-basename.outputs.value }}'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .artifacts/docs/html
          
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4.0.5 
        
  build:
    runs-on: ubuntu-latest
    outputs:
      full-version: ${{ steps.bootstrap.outputs.full-version }}
      major-version: ${{ steps.bootstrap.outputs.major-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docs-builder
        run: |
          dotnet publish "src/docs-builder/docs-builder.csproj" \
            /t:PublishContainer \
            -p DebugType=none \
            -p ContainerUser=1001:1001 \
            -p ContainerBaseImage=${{ env.BASE_IMAGE }} \
            -p ContainerRegistry=ghcr.io \
            -p ContainerImageTags='"${{ env.DOCKER_TAG }};${{ steps.bootstrap.outputs.full-version }}"' \
            -p ContainerRepository=${{ github.repository }} 

      - name: Publish docs-generator
        run: |
          dotnet publish "src/docs-generator/docs-generator.csproj" \
            /t:PublishContainer \
            -p DebugType=none \
            -p ContainerUser=1001:1001 \
            -p ContainerBaseImage=${{ env.BASE_IMAGE_SINGLE }} \
            -p ContainerRegistry=ghcr.io \
            -p ContainerImageTags='"${{ env.DOCKER_TAG }};${{ steps.bootstrap.outputs.full-version }}"' \
            -p ContainerRepository=elastic/docs-generator \
